print("----Sistema Escolar---")
aluno = []
nota = []
nome_do_aluno = input("Qual é o nome do aluno?:")
aluno.append(nome_do_aluno)
nome_do_aluno2 = input("Qual é o nome do aluno?:")
aluno.append(nome_do_aluno2)
nome_do_aluno3 = input("Qual é o nome do aluno?:")
aluno.append(nome_do_aluno3)

nota_do_aluno = float(input("Quais sao as notas dos alunos?:"))
nota.append(nota_do_aluno)
nota_do_aluno2 = float(input("Quais sao as notas dos alunos?:"))
nota.append(nota_do_aluno2)
nota_do_aluno3 = float(input("Quais sao as notas dos alunos?:"))
nota.append(nota_do_aluno3)
print(aluno)
print(nota)
print("A nota mais alta foi:")
print(max(nota))
print("A menor nota foi:")
print(min(nota))
